name: Arcana Language Verification

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        image:
          - 'coqorg/coq:8.14'
          - 'coqorg/coq:8.15'
          - 'coqorg/coq:8.16'
      max-parallel: 4
      fail-fast: true

    steps:
    - uses: actions/checkout@v2
    - uses: coq-community/docker-coq-action@v1
      with:
        opam_file: "coq.opam"
        coq_version: "coqorg/coq:8.16"
        ocaml_version: "default"
        export: "OPAMWITHTEST"
      env:
        OPAMWITHTEST: "true"
