name: Arcana Language Verification

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: coq-community/docker-coq-action@v1
      with:
        opam_file: "lang-verification.opam"
        coq_version: "8.15"
        ocaml_version: "4.07-flambda"
