name: Arcana Language Verification

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        coq_version:
          - "8.15"
          - "dev"
        ocaml_version:
          - "4.07-flambda"
      max-parallel: 4
      fail-fast: true

    steps:
    - uses: actions/checkout@v2
    - uses: coq-community/docker-coq-action@v1
      with:
        opam_file: "coq.opam"
        coq_version: ${{ matrix.coq_version }}
        ocaml_version: ${{ matrix.ocaml_version }}
        export: "OPAMWITHTEST"
      env:
        OPAMWITHTEST: "true"
